version: '3'

volumes:
  myproj_local_postgres_data: {}
  myproj_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: myproj_local_django
    container_name: myproj_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: myproj_production_postgres
    container_name: myproj_local_postgres
    volumes:
      - myproj_local_postgres_data:/var/lib/postgresql/data:Z
      - myproj_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: myproj_local_docs
    container_name: myproj_local_docs
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./myproj:/app/myproj:z
    ports:
      - "9000:9000"
    command: /start-docs

  frontend:
    container_name: frontend
    restart: always
    build:  
      context: ./frontend
      dockerfile: Dockerfile
    image: myproj_frontend_image
    depends_on:
      - django
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d
    ports:
      - 81:80